# change travis.yml to see if that forces build?
language: java
jdk:
  - oraclejdk8
  - openjdk8
branches:
  only:
    - master
    - 3
    - 3.5
    - 4.1
before_install: 'mvn -version'
install: 'mvn clean install -Pfull -DskipTests'

